### ISSUE TITLE
TSR loader open then closes right away

### ISSUE THREAD

**Issue by wizzards581** [argonlefou/TSR_Loader#3] opened 2024-07-12 19:54 UTC
Log file:
[12:48:04.872891] RunGame() => Process created
[12:48:04.888517] Thread 0x00000488 (Id: 10072) created
[12:48:04.888517] Thread 0x0000048C (Id: 10808) created
[12:48:04.888517] Thread 0x00000494 (Id: 9896) created
[12:48:04.904143] RunGame() => Breakpoint reached !
[12:48:04.904143] RunGame() => Process ID: 5628
[12:48:04.904143] RunGame() => Process Memory Base Address: 0x00400000
[12:48:04.904143] RunGame() => Process Handle: 0x000004EC
[12:48:04.935395] CheckMd5() => MD5 hash of C:\Transformers Shadows Rising\Transformers Shadows Rising\tsr standalone\Sega\Transformers2\Transformers2.exe = b3b1f4ad6408d6ee946761a00f761455
[12:48:04.935395] CheckMd5() => MD5 Hash is corresponding to a known target = Transformers Shadow Rising v180605 - Original Dump
[12:48:04.935395] ReadGameDataFromMd5Hash() => Memory File not found : C:\Transformers Shadows Rising\Transformers Shadows Rising\tsr standalone\Sega\Transformers2\MemoryData\b3b1f4ad6408d6ee946761a00f761455.cfg
[12:48:04.935395] RunGame() => Hack complete, leaving the game to run on its own now....

**Comment by argonlefou** [comment] 2024-07-12 21:52
Some people have had that kind of issue, and seems to be happening randomly based on hardware/OS

This is the game itself refusing to boot.
It's possible to get some game log data by running [DebugView](https://learn.microsoft.com/fr-fr/sysinternals/downloads/debugview) before the game (or loader)

Some users had heap size issue, some other file loading issue or shadders error

So far, one of the things that helped some people go through the issue was the following action:

>If anyone else couldn't get Transformers - Rising Shadows to boot, just make the path shorter. I shortened the folder name and took everything out of the "Sega" folder and now it just works

Someone else told me : 

>move all the subfolders from the Sega folder directly into the Transformers - Shadows Rising root....and delete the now empty Sega folder

I can't reproduce the non-booting game on any of my computer, so I can only share what other people found for now

**Comment by wizzards581** [comment] 2024-07-13 08:03
I moved the Sega folder out all the way to C drive and still the same.  I moved all the folders out of Sega and into Transformers Shadows Rising and still the same.

Using Ryzen 2700x, RTX 2060.  Nvidia drivers up to date.  Win 10 is up to date.  I'm curious what a working log file say.

**Comment by argonlefou** [comment] 2024-07-13 12:30
> I moved the Sega folder out all the way to C drive and still the same. I moved all the folders out of Sega and into Transformers Shadows Rising and still the same.

:(

> Using Ryzen 2700x, RTX 2060. Nvidia drivers up to date. Win 10 is up to date. I'm curious what a working log file say.

If you're talking azbout the TSR_Loader log you posted in the first message, a working log would say exactly that.
The loader just creates the process, changes some of  the code code in it to bypass checks and start the process.

The problem is happening afterwards, when the process is running on it's own and crash for some reasons.
The loader is long gone at that point

The DebubView log, on the other hand, would have a lot of information (that would only easily be understood by the one who created the game, but can still try to point a direction for any one else)

**Comment by argonlefou** [comment] 2024-07-13 13:02
So, found an interresting thing trying to mess with the files :  

Just changing a letter in my path make it work, or make it crash on open :  

Game in `D:\TSR\` : [Working Log](https://github.com/user-attachments/files/16202222/TSR_00_OK.LOG)
Game in `D:\TéSR\` : [Crashing Log](https://github.com/user-attachments/files/16202224/TSR_01_Crash.LOG)

So it has to be something with the Path (character ? lenght ?)
I tested with a simple space in the name `D:\T SR` and worked just as good, so it must not be the space character

Another interresting thing I noticed : running the `Transformer2.exe` file directly without the launcher causes the same issue

**Comment by argonlefou** [comment] 2024-07-13 16:09
I finally followed the lead to some D3D API that seem to have trouble with some absolute path names, when creating effects from shader files.

I tried to add a patch in the Launcher to transform absolute path to relative ones, it seems OK at home.

If you wanna try and repport ?

[Transformers2_Launcher_wip.zip](https://github.com/user-attachments/files/16202873/Transformers2_Launcher_wip.zip)

**Comment by wizzards581** [comment] 2024-07-14 01:36
I tried your launcher and still doing the same.  I downgrade nvidia drivers with two previous versions, using your launcher and the original launcher, and same result.

**Comment by argonlefou** [comment] 2024-07-14 10:03
Then I have no more ideas, I've tested the updated launcher on a few different computer (NVIDIA/ATI, GPU/iGPU) and didn't manage to have one crash.

Would you be able to use run the DebugView app from the link I posted in my first answer ? 
You just need to run the exe and run the Loader, and then use the save icon to have a .LOG file that could be helpfull

If possible, use that version of the Launcher, I added a few log outputs
[Transformers2_Launcher_wip2.zip](https://github.com/user-attachments/files/16216396/Transformers2_Launcher_wip2.zip)

**Comment by wizzards581** [comment] 2024-07-14 21:47
[DESKTOP-7RTDSG7.LOG](https://github.com/user-attachments/files/16228877/DESKTOP-7RTDSG7.LOG)

**Comment by argonlefou** [comment] 2024-07-15 05:36
Thanks for the file.

I was not expected the game to crash that fast.

Unfortunately, that `IzErrorTrap: Stop.	` message is used dozens of time in the code and without any more details from the game, there's no way to know where the game is crashing without beeing able to have the same behavior myself and analyse it in real time.

The heap error message is not the issue, as I have it in any of my working logs.

I can just say that the game is crashing when it's initializing it's engine......

I'm almost out of computers to test, I still get a couple of old laptops to test that, hoping I can find a non-working device

**Comment by wizzards581** [comment] 2024-07-16 07:07
I tried it on an old PC, I5 4590, GTX 960 with nvidia drivers from 6/2023 and game boots normally after saving configurator.  Still scratching my head if its software or hardware incompatibility.  Are you using AMD processor?

**Comment by argonlefou** [comment] 2024-07-16 07:20
I tried on both : desktop computer with nvidia 750ti, desktop with AMD iGPU and laptop with AMD iGPU

I still have an old laptop with intel iGpu running Win10 that I hope I can test today or tomorrow

**Comment by argonlefou** [comment] 2024-07-17 05:49
So, I finally found a very old Win7 computer where the game is closing right away.

I don't know if I can fix it (if it's really deep core issue like hardware compatibility) but at least I should be able to see where it's crashing (and maybe why)

I'll keep in touch whatever the results are in a few days, not a lot of free time these days

**Comment by wizzards581** [comment] 2024-07-18 06:34
Thanks for looking into it.  Keep us updated.

**Comment by wizzards581** [comment] 2024-07-21 06:45
Just wanted to let you know, today it magically works now and I don't know why.  There's no changes in win10 updates or nvidia updates.

**Comment by argonlefou** [comment] 2024-07-21 09:45
Well...I found the game crashing when trying to init some debug function with DirectX, that I bypassed.
It then ended crashing trying to initialize XAudio2.7

So with a little help from our friend Google, it turned out that downloading and installing [DirectX End-User Runtimes (June 2010)](https://www.microsoft.com/en-us/download/details.aspx?id=8109) fixed the issue ✌️ 

Luckyly the old computer I tested on was a fresh installed windows without any App, DirectX or redistribuable installed.
I don't think I would have think of that overwise.

Hoping this will fix things for you too.

(I still need to update the launcher with the folder-name patch fix, the one integratted in the first wip version I posted in this issue thread)

If it's correcting your issue, please let me know so that I can put a big red notice on the README 

Edit: Just noticed now your message from this morning, before my reply  😅
So ... maybe some directX changes ?

**Closed as completed** 2024-07-22 12:47 UTC
